// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package com.coen6731.grpc;

public interface QueryRequest1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryRequest1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string year = 1;</code>
   */
  java.lang.String getYear();
  /**
   * <code>string year = 1;</code>
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <code>string state = 2;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 2;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string length = 4;</code>
   */
  java.lang.String getLength();
  /**
   * <code>string length = 4;</code>
   */
  com.google.protobuf.ByteString
      getLengthBytes();

  /**
   * <code>string expense = 5;</code>
   */
  java.lang.String getExpense();
  /**
   * <code>string expense = 5;</code>
   */
  com.google.protobuf.ByteString
      getExpenseBytes();
}
