// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services3.proto

package com.coen6731.grpc;

public interface QueryResponse3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryResponse3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string year = 1;</code>
   */
  java.lang.String getYear();
  /**
   * <code>string year = 1;</code>
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string length = 3;</code>
   */
  java.lang.String getLength();
  /**
   * <code>string length = 3;</code>
   */
  com.google.protobuf.ByteString
      getLengthBytes();

  /**
   * <code>string economical_states = 4;</code>
   */
  java.lang.String getEconomicalStates();
  /**
   * <code>string economical_states = 4;</code>
   */
  com.google.protobuf.ByteString
      getEconomicalStatesBytes();
}
