// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package com.coen6731.grpc;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryRequest1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryResponse1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\"[\n\rQueryRequest1\022\014\n\004yea" +
      "r\030\001 \001(\t\022\r\n\005state\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\016\n\006" +
      "length\030\004 \001(\t\022\017\n\007expense\030\005 \001(\t\"k\n\016QueryRe" +
      "sponse1\022\014\n\004year\030\001 \001(\t\022\r\n\005state\030\002 \001(\t\022\014\n\004" +
      "type\030\003 \001(\t\022\016\n\006length\030\004 \001(\t\022\017\n\007expense\030\005 " +
      "\001(\t\022\r\n\005value\030\006 \001(\t2C\n\rQueryService1\0222\n\017G" +
      "etQueryResult1\022\016.QueryRequest1\032\017.QueryRe" +
      "sponse1B\025\n\021com.coen6731.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryRequest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryRequest1_descriptor,
        new java.lang.String[] { "Year", "State", "Type", "Length", "Expense", });
    internal_static_QueryResponse1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueryResponse1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryResponse1_descriptor,
        new java.lang.String[] { "Year", "State", "Type", "Length", "Expense", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
