// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services4.proto

package com.coen6731.grpc;

public final class Services4 {
  private Services4() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryRequest4_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryResponse4_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017services4.proto\"T\n\rQueryRequest4\022\014\n\004ty" +
      "pe\030\001 \001(\t\022\016\n\006length\030\002 \001(\t\022\022\n\nlatestyear\030\003" +
      " \001(\t\022\021\n\tyearrange\030\004 \001(\t\"t\n\016QueryResponse" +
      "4\022\014\n\004type\030\001 \001(\t\022\016\n\006length\030\002 \001(\t\022\022\n\nlates" +
      "tyear\030\003 \001(\t\022\021\n\tyearrange\030\004 \001(\t\022\035\n\025highes" +
      "t_growth_states\030\005 \001(\t2C\n\rQueryService4\0222" +
      "\n\017GetQueryResult4\022\016.QueryRequest4\032\017.Quer" +
      "yResponse4B\025\n\021com.coen6731.grpcP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryRequest4_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryRequest4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryRequest4_descriptor,
        new java.lang.String[] { "Type", "Length", "Latestyear", "Yearrange", });
    internal_static_QueryResponse4_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueryResponse4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryResponse4_descriptor,
        new java.lang.String[] { "Type", "Length", "Latestyear", "Yearrange", "HighestGrowthStates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
