// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services2.proto

package com.coen6731.grpc;

public interface QueryResponse2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryResponse2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string year = 1;</code>
   */
  java.lang.String getYear();
  /**
   * <code>string year = 1;</code>
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string length = 3;</code>
   */
  java.lang.String getLength();
  /**
   * <code>string length = 3;</code>
   */
  com.google.protobuf.ByteString
      getLengthBytes();

  /**
   * <code>string expensive_states = 4;</code>
   */
  java.lang.String getExpensiveStates();
  /**
   * <code>string expensive_states = 4;</code>
   */
  com.google.protobuf.ByteString
      getExpensiveStatesBytes();
}
