// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services3.proto

package com.coen6731.grpc;

public interface QueryRequest3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryRequest3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string year = 1;</code>
   */
  java.lang.String getYear();
  /**
   * <code>string year = 1;</code>
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string length = 3;</code>
   */
  java.lang.String getLength();
  /**
   * <code>string length = 3;</code>
   */
  com.google.protobuf.ByteString
      getLengthBytes();
}
