// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services4.proto

package com.coen6731.grpc;

public interface QueryResponse4OrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryResponse4)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string length = 2;</code>
   */
  java.lang.String getLength();
  /**
   * <code>string length = 2;</code>
   */
  com.google.protobuf.ByteString
      getLengthBytes();

  /**
   * <code>string latestyear = 3;</code>
   */
  java.lang.String getLatestyear();
  /**
   * <code>string latestyear = 3;</code>
   */
  com.google.protobuf.ByteString
      getLatestyearBytes();

  /**
   * <code>string yearrange = 4;</code>
   */
  java.lang.String getYearrange();
  /**
   * <code>string yearrange = 4;</code>
   */
  com.google.protobuf.ByteString
      getYearrangeBytes();

  /**
   * <code>string highest_growth_states = 5;</code>
   */
  java.lang.String getHighestGrowthStates();
  /**
   * <code>string highest_growth_states = 5;</code>
   */
  com.google.protobuf.ByteString
      getHighestGrowthStatesBytes();
}
