// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services5.proto

package com.coen6731.grpc;

public final class Services5 {
  private Services5() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest5_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryRequest5_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse5_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryResponse5_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017services5.proto\";\n\rQueryRequest5\022\014\n\004ye" +
      "ar\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\016\n\006length\030\003 \001(\t\"U" +
      "\n\016QueryResponse5\022\014\n\004year\030\001 \001(\t\022\014\n\004type\030\002" +
      " \001(\t\022\016\n\006length\030\003 \001(\t\022\027\n\017regions_average\030" +
      "\004 \001(\t2C\n\rQueryService5\0222\n\017GetQueryResult" +
      "5\022\016.QueryRequest5\032\017.QueryResponse5B\025\n\021co" +
      "m.coen6731.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryRequest5_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryRequest5_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryRequest5_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", });
    internal_static_QueryResponse5_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueryResponse5_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryResponse5_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", "RegionsAverage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
